//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryostatControlServer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double He3PumpMaxVoltage {
            get {
                return ((double)(this["He3PumpMaxVoltage"]));
            }
            set {
                this["He3PumpMaxVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double He4PumpMaxVoltage {
            get {
                return ((double)(this["He4PumpMaxVoltage"]));
            }
            set {
                this["He4PumpMaxVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double He4SwitchMaxVoltage {
            get {
                return ((double)(this["He4SwitchMaxVoltage"]));
            }
            set {
                this["He4SwitchMaxVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double He3SwitchMaxVoltage {
            get {
                return ((double)(this["He3SwitchMaxVoltage"]));
            }
            set {
                this["He3SwitchMaxVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double ControllerHe3HeaterVoltage {
            get {
                return ((double)(this["ControllerHe3HeaterVoltage"]));
            }
            set {
                this["ControllerHe3HeaterVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double ControllerHe3SwitchVoltage {
            get {
                return ((double)(this["ControllerHe3SwitchVoltage"]));
            }
            set {
                this["ControllerHe3SwitchVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double ControllerHe4HeaterVoltage {
            get {
                return ((double)(this["ControllerHe4HeaterVoltage"]));
            }
            set {
                this["ControllerHe4HeaterVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double ControllerHe4SwitchVoltage {
            get {
                return ((double)(this["ControllerHe4SwitchVoltage"]));
            }
            set {
                this["ControllerHe4SwitchVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public double ControllerHe7StartTemperature {
            get {
                return ((double)(this["ControllerHe7StartTemperature"]));
            }
            set {
                this["ControllerHe7StartTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public double ControllerHeatSwitchOnTemperature {
            get {
                return ((double)(this["ControllerHeatSwitchOnTemperature"]));
            }
            set {
                this["ControllerHeatSwitchOnTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public double ControllerHeatSwitchSafeValue {
            get {
                return ((double)(this["ControllerHeatSwitchSafeValue"]));
            }
            set {
                this["ControllerHeatSwitchSafeValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double ControllerHeatupTemperature {
            get {
                return ((double)(this["ControllerHeatupTemperature"]));
            }
            set {
                this["ControllerHeatupTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.4")]
        public double ControllerHe4StartTemperature {
            get {
                return ((double)(this["ControllerHe4StartTemperature"]));
            }
            set {
                this["ControllerHe4StartTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double ControllerHe3StartTemperature {
            get {
                return ((double)(this["ControllerHe3StartTemperature"]));
            }
            set {
                this["ControllerHe3StartTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double ControllerDisableHeaterHeatSwitchTemperature {
            get {
                return ((double)(this["ControllerDisableHeaterHeatSwitchTemperature"]));
            }
            set {
                this["ControllerDisableHeaterHeatSwitchTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5")]
        public double ControllerHe3StartMinimalTemperature {
            get {
                return ((double)(this["ControllerHe3StartMinimalTemperature"]));
            }
            set {
                this["ControllerHe3StartMinimalTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double ControllerHe3StartWaitTimeMinutes {
            get {
                return ((double)(this["ControllerHe3StartWaitTimeMinutes"]));
            }
            set {
                this["ControllerHe3StartWaitTimeMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ChangeMe!")]
        public string PasswordToken {
            get {
                return ((string)(this["PasswordToken"]));
            }
            set {
                this["PasswordToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\LoggingCryostat")]
        public string LoggingAddress {
            get {
                return ((string)(this["LoggingAddress"]));
            }
            set {
                this["LoggingAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double ControllerHeaterTemperatureSetpoint {
            get {
                return ((double)(this["ControllerHeaterTemperatureSetpoint"]));
            }
            set {
                this["ControllerHeaterTemperatureSetpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.05")]
        public double ControllerHeaterLowPowerValue {
            get {
                return ((double)(this["ControllerHeaterLowPowerValue"]));
            }
            set {
                this["ControllerHeaterLowPowerValue"] = value;
            }
        }
    }
}
